from __future__ import annotations

# Localized user-interface phrases. Language names are intentionally not translated.
STRINGS = {
"en":{"Help":"Help","Settings":"Settings","Rename":"Rename","Thumbnail":"Thumbnail","Metadata":"Metadata","Language":"Language","Back":"Back","Cancel":"Cancel","Confirm":"Confirm","No Thumbnail":"No Thumbnail","Auto Thumbnail":"Auto Thumbnail","Permanent Thumbnail":"Permanent Thumbnail","Create Your Own Clone Bot":"Create Your Own Clone Bot","File Information":"File Information","Choose an operation:":"Choose an operation:","Send the new filename.":"Send the new filename."},
"ar":{"Help":"مساعدة","Settings":"الإعدادات","Rename":"إعادة تسمية","Thumbnail":"الصورة المصغرة","Metadata":"البيانات الوصفية","Language":"اللغة","Back":"رجوع","Cancel":"إلغاء","Confirm":"تأكيد","No Thumbnail":"بدون صورة مصغرة","Auto Thumbnail":"صورة مصغرة تلقائية","Permanent Thumbnail":"صورة مصغرة دائمة","Create Your Own Clone Bot":"أنشئ بوت نسخ خاصًا بك","File Information":"معلومات الملف","Choose an operation:":"اختر عملية:","Send the new filename.":"أرسل اسم الملف الجديد."},
"hy":{"Help":"Օգնություն","Settings":"Կարգավորումներ","Rename":"Վերանվանել","Thumbnail":"Մանրապատկեր","Metadata":"Մետատվյալներ","Language":"Լեզու","Back":"Հետ","Cancel":"Չեղարկել","Confirm":"Հաստատել","No Thumbnail":"Առանց մանրապատկերի","Auto Thumbnail":"Ավտոմատ մանրապատկեր","Permanent Thumbnail":"Մշտական մանրապատկեր","Create Your Own Clone Bot":"Ստեղծեք ձեր սեփական կլոն բոտը","File Information":"Ֆայլի տեղեկություն","Choose an operation:":"Ընտրեք գործողություն՝","Send the new filename.":"Ուղարկեք նոր ֆայլի անունը։"},
"az":{"Help":"Kömək","Settings":"Parametrlər","Rename":"Adını dəyiş","Thumbnail":"Miniatür","Metadata":"Metaməlumat","Language":"Dil","Back":"Geri","Cancel":"Ləğv et","Confirm":"Təsdiq et","No Thumbnail":"Miniatürsüz","Auto Thumbnail":"Avtomatik miniatür","Permanent Thumbnail":"Daimi miniatür","Create Your Own Clone Bot":"Öz klon botunuzu yaradın","File Information":"Fayl məlumatı","Choose an operation:":"Əməliyyat seçin:","Send the new filename.":"Yeni fayl adını göndərin."},
"bn":{"Help":"সহায়তা","Settings":"সেটিংস","Rename":"নাম পরিবর্তন","Thumbnail":"থাম্বনেইল","Metadata":"মেটাডেটা","Language":"ভাষা","Back":"পিছনে","Cancel":"বাতিল","Confirm":"নিশ্চিত করুন","No Thumbnail":"থাম্বনেইল নেই","Auto Thumbnail":"স্বয়ংক্রিয় থাম্বনেইল","Permanent Thumbnail":"স্থায়ী থাম্বনেইল","Create Your Own Clone Bot":"আপনার নিজস্ব ক্লোন বট তৈরি করুন","File Information":"ফাইলের তথ্য","Choose an operation:":"একটি অপারেশন বেছে নিন:","Send the new filename.":"নতুন ফাইলের নাম পাঠান।"},
"bg":{"Help":"Помощ","Settings":"Настройки","Rename":"Преименуване","Thumbnail":"Миниатюра","Metadata":"Метаданни","Language":"Език","Back":"Назад","Cancel":"Отказ","Confirm":"Потвърди","No Thumbnail":"Без миниатюра","Auto Thumbnail":"Автоматична миниатюра","Permanent Thumbnail":"Постоянна миниатюра","Create Your Own Clone Bot":"Създайте свой собствен клониран бот","File Information":"Информация за файла","Choose an operation:":"Изберете операция:","Send the new filename.":"Изпратете новото име на файла."},
"zh":{"Help":"帮助","Settings":"设置","Rename":"重命名","Thumbnail":"缩略图","Metadata":"元数据","Language":"语言","Back":"返回","Cancel":"取消","Confirm":"确认","No Thumbnail":"无缩略图","Auto Thumbnail":"自动缩略图","Permanent Thumbnail":"永久缩略图","Create Your Own Clone Bot":"创建你自己的克隆机器人","File Information":"文件信息","Choose an operation:":"选择操作：","Send the new filename.":"发送新的文件名。"},
"hr":{"Help":"Pomoć","Settings":"Postavke","Rename":"Preimenuj","Thumbnail":"Sličica","Metadata":"Metapodaci","Language":"Jezik","Back":"Natrag","Cancel":"Otkaži","Confirm":"Potvrdi","No Thumbnail":"Bez sličice","Auto Thumbnail":"Automatska sličica","Permanent Thumbnail":"Trajna sličica","Create Your Own Clone Bot":"Izradite vlastiti klon bota","File Information":"Informacije o datoteci","Choose an operation:":"Odaberite radnju:","Send the new filename.":"Pošaljite novo ime datoteke."},
"cs":{"Help":"Nápověda","Settings":"Nastavení","Rename":"Přejmenovat","Thumbnail":"Náhled","Metadata":"Metadata","Language":"Jazyk","Back":"Zpět","Cancel":"Zrušit","Confirm":"Potvrdit","No Thumbnail":"Bez náhledu","Auto Thumbnail":"Automatický náhled","Permanent Thumbnail":"Trvalý náhled","Create Your Own Clone Bot":"Vytvořte si vlastního klonovacího bota","File Information":"Informace o souboru","Choose an operation:":"Vyberte operaci:","Send the new filename.":"Pošlete nový název souboru."},
"da":{"Help":"Hjælp","Settings":"Indstillinger","Rename":"Omdøb","Thumbnail":"Miniature","Metadata":"Metadata","Language":"Sprog","Back":"Tilbage","Cancel":"Annuller","Confirm":"Bekræft","No Thumbnail":"Ingen miniature","Auto Thumbnail":"Automatisk miniature","Permanent Thumbnail":"Permanent miniature","Create Your Own Clone Bot":"Opret din egen klonbot","File Information":"Filoplysninger","Choose an operation:":"Vælg en handling:","Send the new filename.":"Send det nye filnavn."},
"nl":{"Help":"Help","Settings":"Instellingen","Rename":"Hernoemen","Thumbnail":"Miniatuur","Metadata":"Metadata","Language":"Taal","Back":"Terug","Cancel":"Annuleren","Confirm":"Bevestigen","No Thumbnail":"Geen miniatuur","Auto Thumbnail":"Automatische miniatuur","Permanent Thumbnail":"Permanente miniatuur","Create Your Own Clone Bot":"Maak je eigen kloonbot","File Information":"Bestandsinformatie","Choose an operation:":"Kies een bewerking:","Send the new filename.":"Stuur de nieuwe bestandsnaam."},
"fi":{"Help":"Ohje","Settings":"Asetukset","Rename":"Nimeä uudelleen","Thumbnail":"Pikkukuva","Metadata":"Metatiedot","Language":"Kieli","Back":"Takaisin","Cancel":"Peruuta","Confirm":"Vahvista","No Thumbnail":"Ei pikkukuvaa","Auto Thumbnail":"Automaattinen pikkukuva","Permanent Thumbnail":"Pysyvä pikkukuva","Create Your Own Clone Bot":"Luo oma kloonibotti","File Information":"Tiedoston tiedot","Choose an operation:":"Valitse toiminto:","Send the new filename.":"Lähetä uusi tiedostonimi."},
"fr":{"Help":"Aide","Settings":"Paramètres","Rename":"Renommer","Thumbnail":"Miniature","Metadata":"Métadonnées","Language":"Langue","Back":"Retour","Cancel":"Annuler","Confirm":"Confirmer","No Thumbnail":"Sans miniature","Auto Thumbnail":"Miniature automatique","Permanent Thumbnail":"Miniature permanente","Create Your Own Clone Bot":"Créez votre propre bot clone","File Information":"Informations sur le fichier","Choose an operation:":"Choisissez une opération :","Send the new filename.":"Envoyez le nouveau nom du fichier."},
"ka":{"Help":"დახმარება","Settings":"პარამეტრები","Rename":"გადარქმევა","Thumbnail":"ესკიზი","Metadata":"მეტამონაცემები","Language":"ენა","Back":"უკან","Cancel":"გაუქმება","Confirm":"დადასტურება","No Thumbnail":"ესკიზის გარეშე","Auto Thumbnail":"ავტომატური ესკიზი","Permanent Thumbnail":"მუდმივი ესკიზი","Create Your Own Clone Bot":"შექმენით საკუთარი კლონ-ბოტი","File Information":"ფაილის ინფორმაცია","Choose an operation:":"აირჩიეთ მოქმედება:","Send the new filename.":"გაგზავნეთ ფაილის ახალი სახელი."},
"de":{"Help":"Hilfe","Settings":"Einstellungen","Rename":"Umbenennen","Thumbnail":"Vorschaubild","Metadata":"Metadaten","Language":"Sprache","Back":"Zurück","Cancel":"Abbrechen","Confirm":"Bestätigen","No Thumbnail":"Kein Vorschaubild","Auto Thumbnail":"Automatisches Vorschaubild","Permanent Thumbnail":"Dauerhaftes Vorschaubild","Create Your Own Clone Bot":"Erstelle deinen eigenen Klon-Bot","File Information":"Dateiinformationen","Choose an operation:":"Wählen Sie eine Aktion:","Send the new filename.":"Senden Sie den neuen Dateinamen."},
"el":{"Help":"Βοήθεια","Settings":"Ρυθμίσεις","Rename":"Μετονομασία","Thumbnail":"Μικρογραφία","Metadata":"Μεταδεδομένα","Language":"Γλώσσα","Back":"Πίσω","Cancel":"Ακύρωση","Confirm":"Επιβεβαίωση","No Thumbnail":"Χωρίς μικρογραφία","Auto Thumbnail":"Αυτόματη μικρογραφία","Permanent Thumbnail":"Μόνιμη μικρογραφία","Create Your Own Clone Bot":"Δημιουργήστε το δικό σας κλωνοποιημένο bot","File Information":"Πληροφορίες αρχείου","Choose an operation:":"Επιλέξτε ενέργεια:","Send the new filename.":"Στείλτε το νέο όνομα αρχείου."},
"he":{"Help":"עזרה","Settings":"הגדרות","Rename":"שנה שם","Thumbnail":"תמונה ממוזערת","Metadata":"מטא־נתונים","Language":"שפה","Back":"חזרה","Cancel":"ביטול","Confirm":"אישור","No Thumbnail":"ללא תמונה ממוזערת","Auto Thumbnail":"תמונה ממוזערת אוטומטית","Permanent Thumbnail":"תמונה ממוזערת קבועה","Create Your Own Clone Bot":"צור בוט שכפול משלך","File Information":"פרטי הקובץ","Choose an operation:":"בחר פעולה:","Send the new filename.":"שלח את שם הקובץ החדש."},
"hi":{"Help":"मदद","Settings":"सेटिंग्स","Rename":"नाम बदलें","Thumbnail":"थंबनेल","Metadata":"मेटाडेटा","Language":"भाषा","Back":"वापस","Cancel":"रद्द करें","Confirm":"पुष्टि करें","No Thumbnail":"थंबनेल नहीं","Auto Thumbnail":"ऑटो थंबनेल","Permanent Thumbnail":"स्थायी थंबनेल","Create Your Own Clone Bot":"अपना क्लोन बॉट बनाएं","File Information":"फ़ाइल की जानकारी","Choose an operation:":"एक ऑपरेशन चुनें:","Send the new filename.":"नया फ़ाइल नाम भेजें।"},
"hu":{"Help":"Súgó","Settings":"Beállítások","Rename":"Átnevezés","Thumbnail":"Bélyegkép","Metadata":"Metaadatok","Language":"Nyelv","Back":"Vissza","Cancel":"Mégse","Confirm":"Megerősítés","No Thumbnail":"Nincs bélyegkép","Auto Thumbnail":"Automatikus bélyegkép","Permanent Thumbnail":"Állandó bélyegkép","Create Your Own Clone Bot":"Hozd létre saját klónbotodat","File Information":"Fájlinformáció","Choose an operation:":"Válasszon műveletet:","Send the new filename.":"Küldje el az új fájlnevet."},
"id":{"Help":"Bantuan","Settings":"Pengaturan","Rename":"Ganti nama","Thumbnail":"Gambar mini","Metadata":"Metadata","Language":"Bahasa","Back":"Kembali","Cancel":"Batal","Confirm":"Konfirmasi","No Thumbnail":"Tanpa gambar mini","Auto Thumbnail":"Gambar mini otomatis","Permanent Thumbnail":"Gambar mini permanen","Create Your Own Clone Bot":"Buat bot klon Anda sendiri","File Information":"Informasi file","Choose an operation:":"Pilih operasi:","Send the new filename.":"Kirim nama file baru."},
"it":{"Help":"Aiuto","Settings":"Impostazioni","Rename":"Rinomina","Thumbnail":"Miniatura","Metadata":"Metadati","Language":"Lingua","Back":"Indietro","Cancel":"Annulla","Confirm":"Conferma","No Thumbnail":"Nessuna miniatura","Auto Thumbnail":"Miniatura automatica","Permanent Thumbnail":"Miniatura permanente","Create Your Own Clone Bot":"Crea il tuo bot clone","File Information":"Informazioni sul file","Choose an operation:":"Scegli un'operazione:","Send the new filename.":"Invia il nuovo nome del file."},
"ja":{"Help":"ヘルプ","Settings":"設定","Rename":"名前を変更","Thumbnail":"サムネイル","Metadata":"メタデータ","Language":"言語","Back":"戻る","Cancel":"キャンセル","Confirm":"確認","No Thumbnail":"サムネイルなし","Auto Thumbnail":"自動サムネイル","Permanent Thumbnail":"永久サムネイル","Create Your Own Clone Bot":"自分のクローンボットを作成","File Information":"ファイル情報","Choose an operation:":"操作を選択してください：","Send the new filename.":"新しいファイル名を送信してください。"},
"kk":{"Help":"Көмек","Settings":"Баптаулар","Rename":"Атын өзгерту","Thumbnail":"Нобай","Metadata":"Метадеректер","Language":"Тіл","Back":"Артқа","Cancel":"Бас тарту","Confirm":"Растау","No Thumbnail":"Нобайсыз","Auto Thumbnail":"Автоматты нобай","Permanent Thumbnail":"Тұрақты нобай","Create Your Own Clone Bot":"Өз клон ботыңызды жасаңыз","File Information":"Файл туралы ақпарат","Choose an operation:":"Әрекетті таңдаңыз:","Send the new filename.":"Жаңа файл атауын жіберіңіз."},
"ko":{"Help":"도움말","Settings":"설정","Rename":"이름 변경","Thumbnail":"썸네일","Metadata":"메타데이터","Language":"언어","Back":"뒤로","Cancel":"취소","Confirm":"확인","No Thumbnail":"썸네일 없음","Auto Thumbnail":"자동 썸네일","Permanent Thumbnail":"영구 썸네일","Create Your Own Clone Bot":"나만의 클론 봇 만들기","File Information":"파일 정보","Choose an operation:":"작업을 선택하세요:","Send the new filename.":"새 파일 이름을 보내세요."},
"ms":{"Help":"Bantuan","Settings":"Tetapan","Rename":"Namakan semula","Thumbnail":"Lakaran kecil","Metadata":"Metadata","Language":"Bahasa","Back":"Kembali","Cancel":"Batal","Confirm":"Sahkan","No Thumbnail":"Tiada lakaran kecil","Auto Thumbnail":"Lakaran kecil automatik","Permanent Thumbnail":"Lakaran kecil kekal","Create Your Own Clone Bot":"Cipta bot klon anda sendiri","File Information":"Maklumat fail","Choose an operation:":"Pilih operasi:","Send the new filename.":"Hantar nama fail baharu."},
"ml":{"Help":"സഹായം","Settings":"ക്രമീകരണങ്ങൾ","Rename":"പേര് മാറ്റുക","Thumbnail":"ലഘുചിത്രം","Metadata":"മെറ്റാഡാറ്റ","Language":"ഭാഷ","Back":"പിന്നിലേക്ക്","Cancel":"റദ്ദാക്കുക","Confirm":"സ്ഥിരീകരിക്കുക","No Thumbnail":"ലഘുചിത്രമില്ല","Auto Thumbnail":"ഓട്ടോ ലഘുചിത്രം","Permanent Thumbnail":"സ്ഥിര ലഘുചിത്രം","Create Your Own Clone Bot":"നിങ്ങളുടെ സ്വന്തം ക്ലോൺ ബോട്ട് സൃഷ്ടിക്കുക","File Information":"ഫയൽ വിവരം","Choose an operation:":"ഒരു പ്രവർത്തനം തിരഞ്ഞെടുക്കുക:","Send the new filename.":"പുതിയ ഫയൽനാമം അയയ്ക്കുക."},
"mr":{"Help":"मदत","Settings":"सेटिंग्ज","Rename":"नाव बदला","Thumbnail":"थंबनेल","Metadata":"मेटाडेटा","Language":"भाषा","Back":"मागे","Cancel":"रद्द करा","Confirm":"पुष्टी करा","No Thumbnail":"थंबनेल नाही","Auto Thumbnail":"ऑटो थंबनेल","Permanent Thumbnail":"कायम थंबनेल","Create Your Own Clone Bot":"तुमचा स्वतःचा क्लोन बॉट तयार करा","File Information":"फाइल माहिती","Choose an operation:":"ऑपरेशन निवडा:","Send the new filename.":"नवीन फाइलनाव पाठवा."},
"ne":{"Help":"सहायता","Settings":"सेटिङहरू","Rename":"नाम परिवर्तन","Thumbnail":"थम्बनेल","Metadata":"मेटाडेटा","Language":"भाषा","Back":"पछाडि","Cancel":"रद्द गर्नुहोस्","Confirm":"पुष्टि गर्नुहोस्","No Thumbnail":"थम्बनेल छैन","Auto Thumbnail":"स्वचालित थम्बनेल","Permanent Thumbnail":"स्थायी थम्बनेल","Create Your Own Clone Bot":"आफ्नो क्लोन बोट बनाउनुहोस्","File Information":"फाइल जानकारी","Choose an operation:":"अपरेसन छान्नुहोस्:","Send the new filename.":"नयाँ फाइल नाम पठाउनुहोस्।"},
"no":{"Help":"Hjelp","Settings":"Innstillinger","Rename":"Gi nytt navn","Thumbnail":"Miniatyrbilde","Metadata":"Metadata","Language":"Språk","Back":"Tilbake","Cancel":"Avbryt","Confirm":"Bekreft","No Thumbnail":"Ingen miniatyr","Auto Thumbnail":"Automatisk miniatyr","Permanent Thumbnail":"Permanent miniatyr","Create Your Own Clone Bot":"Lag din egen klonebot","File Information":"Filinformasjon","Choose an operation:":"Velg en handling:","Send the new filename.":"Send det nye filnavnet."},
"or":{"Help":"ସହାୟତା","Settings":"ସେଟିଂସ୍","Rename":"ନାମ ବଦଳାନ୍ତୁ","Thumbnail":"ଥମ୍ବନେଲ୍","Metadata":"ମେଟାଡାଟା","Language":"ଭାଷା","Back":"ପଛକୁ","Cancel":"ବାତିଲ୍","Confirm":"ନିଶ୍ଚିତ କରନ୍ତୁ","No Thumbnail":"ଥମ୍ବନେଲ୍ ନାହିଁ","Auto Thumbnail":"ସ୍ୱୟଂଚାଳିତ ଥମ୍ବନେଲ୍","Permanent Thumbnail":"ସ୍ଥାୟୀ ଥମ୍ବନେଲ୍","Create Your Own Clone Bot":"ନିଜର କ୍ଲୋନ୍ ବଟ୍ ତିଆରି କରନ୍ତୁ","File Information":"ଫାଇଲ୍ ସୂଚନା","Choose an operation:":"ଏକ ଅପରେସନ୍ ବାଛନ୍ତୁ:","Send the new filename.":"ନୂଆ ଫାଇଲ୍ ନାମ ପଠାନ୍ତୁ।"},
"fa":{"Help":"راهنما","Settings":"تنظیمات","Rename":"تغییر نام","Thumbnail":"تصویر بندانگشتی","Metadata":"فراداده","Language":"زبان","Back":"بازگشت","Cancel":"لغو","Confirm":"تأیید","No Thumbnail":"بدون تصویر بندانگشتی","Auto Thumbnail":"تصویر بندانگشتی خودکار","Permanent Thumbnail":"تصویر بندانگشتی دائمی","Create Your Own Clone Bot":"ربات کلون خود را بسازید","File Information":"اطلاعات فایل","Choose an operation:":"یک عملیات را انتخاب کنید:","Send the new filename.":"نام فایل جدید را ارسال کنید."},
"fil":{"Help":"Tulong","Settings":"Mga Setting","Rename":"Palitan ang pangalan","Thumbnail":"Thumbnail","Metadata":"Metadata","Language":"Wika","Back":"Bumalik","Cancel":"Kanselahin","Confirm":"Kumpirmahin","No Thumbnail":"Walang thumbnail","Auto Thumbnail":"Awtomatikong thumbnail","Permanent Thumbnail":"Permanenteng thumbnail","Create Your Own Clone Bot":"Gumawa ng sarili mong clone bot","File Information":"Impormasyon ng file","Choose an operation:":"Pumili ng operasyon:","Send the new filename.":"Ipadala ang bagong filename."},
"pl":{"Help":"Pomoc","Settings":"Ustawienia","Rename":"Zmień nazwę","Thumbnail":"Miniatura","Metadata":"Metadane","Language":"Język","Back":"Wstecz","Cancel":"Anuluj","Confirm":"Potwierdź","No Thumbnail":"Bez miniatury","Auto Thumbnail":"Automatyczna miniatura","Permanent Thumbnail":"Stała miniatura","Create Your Own Clone Bot":"Utwórz własnego bota klonującego","File Information":"Informacje o pliku","Choose an operation:":"Wybierz operację:","Send the new filename.":"Wyślij nową nazwę pliku."},
"pt":{"Help":"Ajuda","Settings":"Configurações","Rename":"Renomear","Thumbnail":"Miniatura","Metadata":"Metadados","Language":"Idioma","Back":"Voltar","Cancel":"Cancelar","Confirm":"Confirmar","No Thumbnail":"Sem miniatura","Auto Thumbnail":"Miniatura automática","Permanent Thumbnail":"Miniatura permanente","Create Your Own Clone Bot":"Crie seu próprio bot clone","File Information":"Informações do arquivo","Choose an operation:":"Escolha uma operação:","Send the new filename.":"Envie o novo nome do arquivo."},
"pa":{"Help":"ਮਦਦ","Settings":"ਸੈਟਿੰਗਾਂ","Rename":"ਨਾਂ ਬਦਲੋ","Thumbnail":"ਥੰਬਨੇਲ","Metadata":"ਮੈਟਾਡਾਟਾ","Language":"ਭਾਸ਼ਾ","Back":"ਵਾਪਸ","Cancel":"ਰੱਦ ਕਰੋ","Confirm":"ਪੁਸ਼ਟੀ ਕਰੋ","No Thumbnail":"ਥੰਬਨੇਲ ਨਹੀਂ","Auto Thumbnail":"ਆਟੋ ਥੰਬਨੇਲ","Permanent Thumbnail":"ਸਥਾਈ ਥੰਬਨੇਲ","Create Your Own Clone Bot":"ਆਪਣਾ ਕਲੋਨ ਬੋਟ ਬਣਾਓ","File Information":"ਫਾਈਲ ਦੀ ਜਾਣਕਾਰੀ","Choose an operation:":"ਇੱਕ ਕਾਰਵਾਈ ਚੁਣੋ:","Send the new filename.":"ਨਵਾਂ ਫਾਈਲ ਨਾਮ ਭੇਜੋ।"},
"ro":{"Help":"Ajutor","Settings":"Setări","Rename":"Redenumește","Thumbnail":"Miniatură","Metadata":"Metadate","Language":"Limbă","Back":"Înapoi","Cancel":"Anulează","Confirm":"Confirmă","No Thumbnail":"Fără miniatură","Auto Thumbnail":"Miniatură automată","Permanent Thumbnail":"Miniatură permanentă","Create Your Own Clone Bot":"Creează-ți propriul bot clonă","File Information":"Informații despre fișier","Choose an operation:":"Alege o operațiune:","Send the new filename.":"Trimite noul nume al fișierului."},
"ru":{"Help":"Помощь","Settings":"Настройки","Rename":"Переименовать","Thumbnail":"Миниатюра","Metadata":"Метаданные","Language":"Язык","Back":"Назад","Cancel":"Отмена","Confirm":"Подтвердить","No Thumbnail":"Без миниатюры","Auto Thumbnail":"Автоматическая миниатюра","Permanent Thumbnail":"Постоянная миниатюра","Create Your Own Clone Bot":"Создайте своего клонированного бота","File Information":"Информация о файле","Choose an operation:":"Выберите операцию:","Send the new filename.":"Отправьте новое имя файла."},
"sr":{"Help":"Помоћ","Settings":"Подешавања","Rename":"Преименуј","Thumbnail":"Сличица","Metadata":"Метаподаци","Language":"Језик","Back":"Назад","Cancel":"Откажи","Confirm":"Потврди","No Thumbnail":"Без сличице","Auto Thumbnail":"Аутоматска сличица","Permanent Thumbnail":"Трајна сличица","Create Your Own Clone Bot":"Направите свој клон бота","File Information":"Информације о датотеци","Choose an operation:":"Изаберите радњу:","Send the new filename.":"Пошаљите нови назив датотеке."},
"sk":{"Help":"Pomoc","Settings":"Nastavenia","Rename":"Premenovať","Thumbnail":"Miniatúra","Metadata":"Metadáta","Language":"Jazyk","Back":"Späť","Cancel":"Zrušiť","Confirm":"Potvrdiť","No Thumbnail":"Bez miniatúry","Auto Thumbnail":"Automatická miniatúra","Permanent Thumbnail":"Trvalá miniatúra","Create Your Own Clone Bot":"Vytvorte si vlastného klonovacieho bota","File Information":"Informácie o súbore","Choose an operation:":"Vyberte operáciu:","Send the new filename.":"Pošlite nový názov súboru."},
"sl":{"Help":"Pomoč","Settings":"Nastavitve","Rename":"Preimenuj","Thumbnail":"Sličica","Metadata":"Metapodatki","Language":"Jezik","Back":"Nazaj","Cancel":"Prekliči","Confirm":"Potrdi","No Thumbnail":"Brez sličice","Auto Thumbnail":"Samodejna sličica","Permanent Thumbnail":"Stalna sličica","Create Your Own Clone Bot":"Ustvari svoj klonski bot","File Information":"Informacije o datoteki","Choose an operation:":"Izberite dejanje:","Send the new filename.":"Pošljite novo ime datoteke."},
"es":{"Help":"Ayuda","Settings":"Configuración","Rename":"Renombrar","Thumbnail":"Miniatura","Metadata":"Metadatos","Language":"Idioma","Back":"Atrás","Cancel":"Cancelar","Confirm":"Confirmar","No Thumbnail":"Sin miniatura","Auto Thumbnail":"Miniatura automática","Permanent Thumbnail":"Miniatura permanente","Create Your Own Clone Bot":"Crea tu propio bot clon","File Information":"Información del archivo","Choose an operation:":"Elige una operación:","Send the new filename.":"Envía el nuevo nombre del archivo."},
"si":{"Help":"උදව්","Settings":"සැකසුම්","Rename":"නම වෙනස් කරන්න","Thumbnail":"කුඩා රූපය","Metadata":"මෙටාදත්ත","Language":"භාෂාව","Back":"ආපසු","Cancel":"අවලංගු කරන්න","Confirm":"තහවුරු කරන්න","No Thumbnail":"කුඩා රූපයක් නැත","Auto Thumbnail":"ස්වයංක්‍රීය කුඩා රූපය","Permanent Thumbnail":"ස්ථිර කුඩා රූපය","Create Your Own Clone Bot":"ඔබේම ක්ලෝන බොට් එක සාදන්න","File Information":"ගොනු තොරතුරු","Choose an operation:":"ක්‍රියාවක් තෝරන්න:","Send the new filename.":"නව ගොනු නාමය යවන්න."},
"sv":{"Help":"Hjälp","Settings":"Inställningar","Rename":"Byt namn","Thumbnail":"Miniatyrbild","Metadata":"Metadata","Language":"Språk","Back":"Tillbaka","Cancel":"Avbryt","Confirm":"Bekräfta","No Thumbnail":"Ingen miniatyrbild","Auto Thumbnail":"Automatisk miniatyrbild","Permanent Thumbnail":"Permanent miniatyrbild","Create Your Own Clone Bot":"Skapa din egen klonbot","File Information":"Filinformation","Choose an operation:":"Välj en åtgärd:","Send the new filename.":"Skicka det nya filnamnet."},
"th":{"Help":"ช่วยเหลือ","Settings":"การตั้งค่า","Rename":"เปลี่ยนชื่อ","Thumbnail":"ภาพขนาดย่อ","Metadata":"ข้อมูลเมตา","Language":"ภาษา","Back":"ย้อนกลับ","Cancel":"ยกเลิก","Confirm":"ยืนยัน","No Thumbnail":"ไม่มีภาพขนาดย่อ","Auto Thumbnail":"ภาพขนาดย่ออัตโนมัติ","Permanent Thumbnail":"ภาพขนาดย่อถาวร","Create Your Own Clone Bot":"สร้างบอตโคลนของคุณเอง","File Information":"ข้อมูลไฟล์","Choose an operation:":"เลือกการดำเนินการ:","Send the new filename.":"ส่งชื่อไฟล์ใหม่"},
"ta":{"Help":"உதவி","Settings":"அமைப்புகள்","Rename":"மறுபெயரிடு","Thumbnail":"சிறுபடம்","Metadata":"மெட்டாடேட்டா","Language":"மொழி","Back":"பின்செல்","Cancel":"ரத்துசெய்","Confirm":"உறுதிப்படுத்து","No Thumbnail":"சிறுபடம் இல்லை","Auto Thumbnail":"தானியங்கி சிறுபடம்","Permanent Thumbnail":"நிரந்தர சிறுபடம்","Create Your Own Clone Bot":"உங்கள் சொந்த குளோன் போட்டை உருவாக்கவும்","File Information":"கோப்பு தகவல்","Choose an operation:":"ஒரு செயல்பாட்டைத் தேர்ந்தெடுக்கவும்:","Send the new filename.":"புதிய கோப்புப்பெயரை அனுப்பவும்."},
"te":{"Help":"సహాయం","Settings":"సెట్టింగ్స్","Rename":"పేరు మార్చండి","Thumbnail":"థంబ్‌నెయిల్","Metadata":"మెటాడేటా","Language":"భాష","Back":"వెనక్కి","Cancel":"రద్దు చేయండి","Confirm":"నిర్ధారించండి","No Thumbnail":"థంబ్‌నెయిల్ వద్దు","Auto Thumbnail":"ఆటో థంబ్‌నెయిల్","Permanent Thumbnail":"శాశ్వత థంబ్‌నెయిల్","Create Your Own Clone Bot":"మీ స్వంత క్లోన్ బాట్‌ను సృష్టించండి","File Information":"ఫైల్ సమాచారం","Choose an operation:":"ఒక ఆపరేషన్‌ను ఎంచుకోండి:","Send the new filename.":"కొత్త ఫైల్ పేరు పంపండి."},
"tr":{"Help":"Yardım","Settings":"Ayarlar","Rename":"Yeniden adlandır","Thumbnail":"Küçük resim","Metadata":"Meta veriler","Language":"Dil","Back":"Geri","Cancel":"İptal","Confirm":"Onayla","No Thumbnail":"Küçük resim yok","Auto Thumbnail":"Otomatik küçük resim","Permanent Thumbnail":"Kalıcı küçük resim","Create Your Own Clone Bot":"Kendi klon botunuzu oluşturun","File Information":"Dosya bilgileri","Choose an operation:":"Bir işlem seçin:","Send the new filename.":"Yeni dosya adını gönderin."},
"uk":{"Help":"Допомога","Settings":"Налаштування","Rename":"Перейменувати","Thumbnail":"Мініатюра","Metadata":"Метадані","Language":"Мова","Back":"Назад","Cancel":"Скасувати","Confirm":"Підтвердити","No Thumbnail":"Без мініатюри","Auto Thumbnail":"Автоматична мініатюра","Permanent Thumbnail":"Постійна мініатюра","Create Your Own Clone Bot":"Створіть власного бота-клона","File Information":"Інформація про файл","Choose an operation:":"Оберіть операцію:","Send the new filename.":"Надішліть нову назву файлу."},
"ur":{"Help":"مدد","Settings":"ترتیبات","Rename":"نام تبدیل کریں","Thumbnail":"تھمب نیل","Metadata":"میٹا ڈیٹا","Language":"زبان","Back":"واپس","Cancel":"منسوخ کریں","Confirm":"تصدیق کریں","No Thumbnail":"تھمب نیل نہیں","Auto Thumbnail":"خودکار تھمب نیل","Permanent Thumbnail":"مستقل تھمب نیل","Create Your Own Clone Bot":"اپنا کلون بوٹ بنائیں","File Information":"فائل کی معلومات","Choose an operation:":"ایک آپریشن منتخب کریں:","Send the new filename.":"نیا فائل نام بھیجیں۔"},
"uz":{"Help":"Yordam","Settings":"Sozlamalar","Rename":"Nomini o‘zgartirish","Thumbnail":"Eskiz","Metadata":"Metama’lumotlar","Language":"Til","Back":"Orqaga","Cancel":"Bekor qilish","Confirm":"Tasdiqlash","No Thumbnail":"Eskizsiz","Auto Thumbnail":"Avtomatik eskiz","Permanent Thumbnail":"Doimiy eskiz","Create Your Own Clone Bot":"O‘z klon botingizni yarating","File Information":"Fayl ma’lumotlari","Choose an operation:":"Amalni tanlang:","Send the new filename.":"Yangi fayl nomini yuboring."},
"vi":{"Help":"Trợ giúp","Settings":"Cài đặt","Rename":"Đổi tên","Thumbnail":"Ảnh thu nhỏ","Metadata":"Siêu dữ liệu","Language":"Ngôn ngữ","Back":"Quay lại","Cancel":"Hủy","Confirm":"Xác nhận","No Thumbnail":"Không có ảnh thu nhỏ","Auto Thumbnail":"Ảnh thu nhỏ tự động","Permanent Thumbnail":"Ảnh thu nhỏ cố định","Create Your Own Clone Bot":"Tạo bot clone của riêng bạn","File Information":"Thông tin tệp","Choose an operation:":"Chọn thao tác:","Send the new filename.":"Gửi tên tệp mới."},
}

LANGUAGE_CODES = tuple(STRINGS)

# Extended UI translations used by command pages and localized buttons.
EXTENDED_STRINGS = {
    "en": {"Custom Thumbnail":"Custom Thumbnail","Add Thumbnail":"Add Thumbnail","Replace Thumbnail":"Replace Thumbnail","Show Thumbnail":"Show Thumbnail","Delete Custom":"Delete Custom","Plan":"Plan","Home":"Home","Choose a plan":"Choose a plan","Rename Page":"Rename Page","Thumbnail Page":"Thumbnail Page","Language Page":"Language Page"} ,
    "ar": {"Custom Thumbnail":"صورة مصغرة مخصصة","Add Thumbnail":"إضافة صورة مصغرة","Replace Thumbnail":"استبدال الصورة المصغرة","Show Thumbnail":"عرض الصورة المصغرة","Delete Custom":"حذف المخصصة","Plan":"الخطة","Home":"الرئيسية","Choose a plan":"اختر خطة","Rename Page":"صفحة إعادة التسمية","Thumbnail Page":"صفحة الصورة المصغرة","Language Page":"صفحة اللغة"} ,
    "hy": {"Custom Thumbnail":"Հատուկ մանրապատկեր","Add Thumbnail":"Ավելացնել մանրապատկեր","Replace Thumbnail":"Փոխարինել մանրապատկերը","Show Thumbnail":"Ցուցադրել մանրապատկերը","Delete Custom":"Ջնջել հատուկը","Plan":"Պլան","Home":"Գլխավոր","Choose a plan":"Ընտրեք պլան","Rename Page":"Վերանվանման էջ","Thumbnail Page":"Մանրապատկերի էջ","Language Page":"Լեզվի էջ"} ,
    "az": {"Custom Thumbnail":"Xüsusi miniatür","Add Thumbnail":"Miniatür əlavə et","Replace Thumbnail":"Miniatürü dəyişdir","Show Thumbnail":"Miniatürü göstər","Delete Custom":"Xüsusini sil","Plan":"Plan","Home":"Ana səhifə","Choose a plan":"Plan seçin","Rename Page":"Ad dəyişdirmə səhifəsi","Thumbnail Page":"Miniatür səhifəsi","Language Page":"Dil səhifəsi"} ,
    "bn": {"Custom Thumbnail":"কাস্টম থাম্বনেইল","Add Thumbnail":"থাম্বনেইল যোগ করুন","Replace Thumbnail":"থাম্বনেইল প্রতিস্থাপন করুন","Show Thumbnail":"থাম্বনেইল দেখান","Delete Custom":"কাস্টমটি মুছুন","Plan":"প্ল্যান","Home":"হোম","Choose a plan":"একটি প্ল্যান বেছে নিন","Rename Page":"নাম পরিবর্তন পৃষ্ঠা","Thumbnail Page":"থাম্বনেইল পৃষ্ঠা","Language Page":"ভাষা পৃষ্ঠা"} ,
    "bg": {"Custom Thumbnail":"Персонализирана миниатюра","Add Thumbnail":"Добави миниатюра","Replace Thumbnail":"Замени миниатюрата","Show Thumbnail":"Покажи миниатюрата","Delete Custom":"Изтрий персонализираната","Plan":"План","Home":"Начало","Choose a plan":"Изберете план","Rename Page":"Страница за преименуване","Thumbnail Page":"Страница за миниатюра","Language Page":"Страница за език"} ,
    "zh": {"Custom Thumbnail":"自定义缩略图","Add Thumbnail":"添加缩略图","Replace Thumbnail":"替换缩略图","Show Thumbnail":"显示缩略图","Delete Custom":"删除自定义缩略图","Plan":"套餐","Home":"主页","Choose a plan":"选择套餐","Rename Page":"重命名页面","Thumbnail Page":"缩略图页面","Language Page":"语言页面"} ,
    "hr": {"Custom Thumbnail":"Prilagođena sličica","Add Thumbnail":"Dodaj sličicu","Replace Thumbnail":"Zamijeni sličicu","Show Thumbnail":"Prikaži sličicu","Delete Custom":"Obriši prilagođenu","Plan":"Plan","Home":"Početna","Choose a plan":"Odaberite plan","Rename Page":"Stranica za preimenovanje","Thumbnail Page":"Stranica sličice","Language Page":"Stranica jezika"} ,
    "cs": {"Custom Thumbnail":"Vlastní náhled","Add Thumbnail":"Přidat náhled","Replace Thumbnail":"Nahradit náhled","Show Thumbnail":"Zobrazit náhled","Delete Custom":"Smazat vlastní","Plan":"Plán","Home":"Domů","Choose a plan":"Vyberte plán","Rename Page":"Stránka přejmenování","Thumbnail Page":"Stránka náhledu","Language Page":"Stránka jazyka"} ,
    "da": {"Custom Thumbnail":"Brugerdefineret miniature","Add Thumbnail":"Tilføj miniature","Replace Thumbnail":"Erstat miniature","Show Thumbnail":"Vis miniature","Delete Custom":"Slet brugerdefineret","Plan":"Plan","Home":"Hjem","Choose a plan":"Vælg en plan","Rename Page":"Omdøbningsside","Thumbnail Page":"Miniatureside","Language Page":"Sprogside"} ,
    "nl": {"Custom Thumbnail":"Aangepaste miniatuur","Add Thumbnail":"Miniatuur toevoegen","Replace Thumbnail":"Miniatuur vervangen","Show Thumbnail":"Miniatuur tonen","Delete Custom":"Aangepaste verwijderen","Plan":"Plan","Home":"Home","Choose a plan":"Kies een plan","Rename Page":"Hernoemingspagina","Thumbnail Page":"Miniatuurpagina","Language Page":"Taalpagina"} ,
    "fi": {"Custom Thumbnail":"Mukautettu pikkukuva","Add Thumbnail":"Lisää pikkukuva","Replace Thumbnail":"Korvaa pikkukuva","Show Thumbnail":"Näytä pikkukuva","Delete Custom":"Poista mukautettu","Plan":"Paketti","Home":"Etusivu","Choose a plan":"Valitse paketti","Rename Page":"Uudelleennimeämissivu","Thumbnail Page":"Pikkukuvansivu","Language Page":"Kielisivu"} ,
    "fr": {"Custom Thumbnail":"Miniature personnalisée","Add Thumbnail":"Ajouter une miniature","Replace Thumbnail":"Remplacer la miniature","Show Thumbnail":"Afficher la miniature","Delete Custom":"Supprimer la personnalisée","Plan":"Forfait","Home":"Accueil","Choose a plan":"Choisissez un forfait","Rename Page":"Page de renommage","Thumbnail Page":"Page miniature","Language Page":"Page de langue"} ,
    "ka": {"Custom Thumbnail":"მორგებული ესკიზი","Add Thumbnail":"ესკიზის დამატება","Replace Thumbnail":"ესკიზის ჩანაცვლება","Show Thumbnail":"ესკიზის ჩვენება","Delete Custom":"მორგებულის წაშლა","Plan":"გეგმა","Home":"მთავარი","Choose a plan":"აირჩიეთ გეგმა","Rename Page":"გადარქმევის გვერდი","Thumbnail Page":"ესკიზის გვერდი","Language Page":"ენის გვერდი"} ,
    "de": {"Custom Thumbnail":"Benutzerdefiniertes Vorschaubild","Add Thumbnail":"Vorschaubild hinzufügen","Replace Thumbnail":"Vorschaubild ersetzen","Show Thumbnail":"Vorschaubild anzeigen","Delete Custom":"Benutzerdefiniertes löschen","Plan":"Plan","Home":"Startseite","Choose a plan":"Wählen Sie einen Plan","Rename Page":"Umbenennungsseite","Thumbnail Page":"Vorschaubildseite","Language Page":"Sprachseite"} ,
    "el": {"Custom Thumbnail":"Προσαρμοσμένη μικρογραφία","Add Thumbnail":"Προσθήκη μικρογραφίας","Replace Thumbnail":"Αντικατάσταση μικρογραφίας","Show Thumbnail":"Εμφάνιση μικρογραφίας","Delete Custom":"Διαγραφή προσαρμοσμένης","Plan":"Πλάνο","Home":"Αρχική","Choose a plan":"Επιλέξτε πλάνο","Rename Page":"Σελίδα μετονομασίας","Thumbnail Page":"Σελίδα μικρογραφίας","Language Page":"Σελίδα γλώσσας"} ,
    "he": {"Custom Thumbnail":"תמונה ממוזערת מותאמת אישית","Add Thumbnail":"הוסף תמונה ממוזערת","Replace Thumbnail":"החלף תמונה ממוזערת","Show Thumbnail":"הצג תמונה ממוזערת","Delete Custom":"מחק מותאם אישית","Plan":"תוכנית","Home":"בית","Choose a plan":"בחר תוכנית","Rename Page":"דף שינוי שם","Thumbnail Page":"דף תמונה ממוזערת","Language Page":"דף שפה"} ,
    "hi": {"Custom Thumbnail":"कस्टम थंबनेल","Add Thumbnail":"थंबनेल जोड़ें","Replace Thumbnail":"थंबनेल बदलें","Show Thumbnail":"थंबनेल दिखाएँ","Delete Custom":"कस्टम हटाएँ","Plan":"प्लान","Home":"होम","Choose a plan":"एक प्लान चुनें","Rename Page":"नाम बदलने का पेज","Thumbnail Page":"थंबनेल पेज","Language Page":"भाषा पेज"} ,
    "hu": {"Custom Thumbnail":"Egyéni bélyegkép","Add Thumbnail":"Bélyegkép hozzáadása","Replace Thumbnail":"Bélyegkép cseréje","Show Thumbnail":"Bélyegkép megjelenítése","Delete Custom":"Egyéni törlése","Plan":"Csomag","Home":"Főoldal","Choose a plan":"Válasszon csomagot","Rename Page":"Átnevezési oldal","Thumbnail Page":"Bélyegkép oldal","Language Page":"Nyelvi oldal"} ,
    "id": {"Custom Thumbnail":"Gambar mini kustom","Add Thumbnail":"Tambah gambar mini","Replace Thumbnail":"Ganti gambar mini","Show Thumbnail":"Tampilkan gambar mini","Delete Custom":"Hapus kustom","Plan":"Paket","Home":"Beranda","Choose a plan":"Pilih paket","Rename Page":"Halaman ganti nama","Thumbnail Page":"Halaman gambar mini","Language Page":"Halaman bahasa"} ,
    "it": {"Custom Thumbnail":"Miniatura personalizzata","Add Thumbnail":"Aggiungi miniatura","Replace Thumbnail":"Sostituisci miniatura","Show Thumbnail":"Mostra miniatura","Delete Custom":"Elimina personalizzata","Plan":"Piano","Home":"Home","Choose a plan":"Scegli un piano","Rename Page":"Pagina rinomina","Thumbnail Page":"Pagina miniatura","Language Page":"Pagina lingua"} ,
    "ja": {"Custom Thumbnail":"カスタムサムネイル","Add Thumbnail":"サムネイルを追加","Replace Thumbnail":"サムネイルを置換","Show Thumbnail":"サムネイルを表示","Delete Custom":"カスタムを削除","Plan":"プラン","Home":"ホーム","Choose a plan":"プランを選択","Rename Page":"名前変更ページ","Thumbnail Page":"サムネイルページ","Language Page":"言語ページ"} ,
    "kk": {"Custom Thumbnail":"Арнайы нобай","Add Thumbnail":"Нобай қосу","Replace Thumbnail":"Нобайды ауыстыру","Show Thumbnail":"Нобайды көрсету","Delete Custom":"Арнайыны жою","Plan":"Жоспар","Home":"Басты бет","Choose a plan":"Жоспарды таңдаңыз","Rename Page":"Атын өзгерту беті","Thumbnail Page":"Нобай беті","Language Page":"Тіл беті"} ,
    "ko": {"Custom Thumbnail":"사용자 지정 썸네일","Add Thumbnail":"썸네일 추가","Replace Thumbnail":"썸네일 교체","Show Thumbnail":"썸네일 보기","Delete Custom":"사용자 지정 삭제","Plan":"플랜","Home":"홈","Choose a plan":"플랜 선택","Rename Page":"이름 변경 페이지","Thumbnail Page":"썸네일 페이지","Language Page":"언어 페이지"} ,
    "ms": {"Custom Thumbnail":"Lakaran kecil tersuai","Add Thumbnail":"Tambah lakaran kecil","Replace Thumbnail":"Ganti lakaran kecil","Show Thumbnail":"Tunjukkan lakaran kecil","Delete Custom":"Padam tersuai","Plan":"Pelan","Home":"Utama","Choose a plan":"Pilih pelan","Rename Page":"Halaman nama semula","Thumbnail Page":"Halaman lakaran kecil","Language Page":"Halaman bahasa"} ,
    "ml": {"Custom Thumbnail":"ഇഷ്ടാനുസൃത ലഘുചിത്രം","Add Thumbnail":"ലഘുചിത്രം ചേർക്കുക","Replace Thumbnail":"ലഘുചിത്രം മാറ്റിസ്ഥാപിക്കുക","Show Thumbnail":"ലഘുചിത്രം കാണിക്കുക","Delete Custom":"ഇഷ്ടാനുസൃതം ഇല്ലാതാക്കുക","Plan":"പ്ലാൻ","Home":"ഹോം","Choose a plan":"ഒരു പ്ലാൻ തിരഞ്ഞെടുക്കുക","Rename Page":"പേര് മാറ്റൽ പേജ്","Thumbnail Page":"ലഘുചിത്ര പേജ്","Language Page":"ഭാഷാ പേജ്"} ,
    "mr": {"Custom Thumbnail":"कस्टम थंबनेल","Add Thumbnail":"थंबनेल जोडा","Replace Thumbnail":"थंबनेल बदला","Show Thumbnail":"थंबनेल दाखवा","Delete Custom":"कस्टम हटवा","Plan":"प्लॅन","Home":"होम","Choose a plan":"प्लॅन निवडा","Rename Page":"नाव बदलण्याचे पृष्ठ","Thumbnail Page":"थंबनेल पृष्ठ","Language Page":"भाषा पृष्ठ"} ,
    "ne": {"Custom Thumbnail":"अनुकूल थम्बनेल","Add Thumbnail":"थम्बनेल थप्नुहोस्","Replace Thumbnail":"थम्बनेल प्रतिस्थापन गर्नुहोस्","Show Thumbnail":"थम्बनेल देखाउनुहोस्","Delete Custom":"अनुकूल हटाउनुहोस्","Plan":"योजना","Home":"होम","Choose a plan":"योजना छान्नुहोस्","Rename Page":"नाम परिवर्तन पृष्ठ","Thumbnail Page":"थम्बनेल पृष्ठ","Language Page":"भाषा पृष्ठ"} ,
    "no": {"Custom Thumbnail":"Egendefinert miniatyr","Add Thumbnail":"Legg til miniatyr","Replace Thumbnail":"Bytt miniatyr","Show Thumbnail":"Vis miniatyr","Delete Custom":"Slett egendefinert","Plan":"Plan","Home":"Hjem","Choose a plan":"Velg en plan","Rename Page":"Omdøpningsside","Thumbnail Page":"Miniatyrside","Language Page":"Språkside"} ,
    "or": {"Custom Thumbnail":"କଷ୍ଟମ୍ ଥମ୍ବନେଲ୍","Add Thumbnail":"ଥମ୍ବନେଲ୍ ଯୋଡନ୍ତୁ","Replace Thumbnail":"ଥମ୍ବନେଲ୍ ବଦଳାନ୍ତୁ","Show Thumbnail":"ଥମ୍ବନେଲ୍ ଦେଖନ୍ତୁ","Delete Custom":"କଷ୍ଟମ୍ ଡିଲିଟ୍ କରନ୍ତୁ","Plan":"ଯୋଜନା","Home":"ମୁଖ୍ୟ","Choose a plan":"ଏକ ଯୋଜନା ବାଛନ୍ତୁ","Rename Page":"ନାମ ପରିବର୍ତ୍ତନ ପୃଷ୍ଠା","Thumbnail Page":"ଥମ୍ବନେଲ୍ ପୃଷ୍ଠା","Language Page":"ଭାଷା ପୃଷ୍ଠା"} ,
    "fa": {"Custom Thumbnail":"تصویر بندانگشتی سفارشی","Add Thumbnail":"افزودن تصویر بندانگشتی","Replace Thumbnail":"جایگزینی تصویر بندانگشتی","Show Thumbnail":"نمایش تصویر بندانگشتی","Delete Custom":"حذف سفارشی","Plan":"طرح","Home":"خانه","Choose a plan":"یک طرح انتخاب کنید","Rename Page":"صفحه تغییر نام","Thumbnail Page":"صفحه تصویر بندانگشتی","Language Page":"صفحه زبان"} ,
    "fil": {"Custom Thumbnail":"Custom na thumbnail","Add Thumbnail":"Magdagdag ng thumbnail","Replace Thumbnail":"Palitan ang thumbnail","Show Thumbnail":"Ipakita ang thumbnail","Delete Custom":"Tanggalin ang custom","Plan":"Plano","Home":"Home","Choose a plan":"Pumili ng plano","Rename Page":"Pahina ng pagpapalit ng pangalan","Thumbnail Page":"Pahina ng thumbnail","Language Page":"Pahina ng wika"} ,
    "pl": {"Custom Thumbnail":"Niestandardowa miniatura","Add Thumbnail":"Dodaj miniaturę","Replace Thumbnail":"Zastąp miniaturę","Show Thumbnail":"Pokaż miniaturę","Delete Custom":"Usuń niestandardową","Plan":"Plan","Home":"Strona główna","Choose a plan":"Wybierz plan","Rename Page":"Strona zmiany nazwy","Thumbnail Page":"Strona miniatury","Language Page":"Strona języka"} ,
    "pt": {"Custom Thumbnail":"Miniatura personalizada","Add Thumbnail":"Adicionar miniatura","Replace Thumbnail":"Substituir miniatura","Show Thumbnail":"Mostrar miniatura","Delete Custom":"Excluir personalizada","Plan":"Plano","Home":"Início","Choose a plan":"Escolha um plano","Rename Page":"Página de renomeação","Thumbnail Page":"Página de miniatura","Language Page":"Página de idioma"} ,
    "pa": {"Custom Thumbnail":"ਕਸਟਮ ਥੰਬਨੇਲ","Add Thumbnail":"ਥੰਬਨੇਲ ਜੋੜੋ","Replace Thumbnail":"ਥੰਬਨੇਲ ਬਦਲੋ","Show Thumbnail":"ਥੰਬਨੇਲ ਦਿਖਾਓ","Delete Custom":"ਕਸਟਮ ਮਿਟਾਓ","Plan":"ਪਲਾਨ","Home":"ਹੋਮ","Choose a plan":"ਇੱਕ ਪਲਾਨ ਚੁਣੋ","Rename Page":"ਨਾਂ ਬਦਲਣ ਵਾਲਾ ਪੰਨਾ","Thumbnail Page":"ਥੰਬਨੇਲ ਪੰਨਾ","Language Page":"ਭਾਸ਼ਾ ਪੰਨਾ"} ,
    "ro": {"Custom Thumbnail":"Miniatură personalizată","Add Thumbnail":"Adaugă miniatură","Replace Thumbnail":"Înlocuiește miniatura","Show Thumbnail":"Afișează miniatura","Delete Custom":"Șterge personalizata","Plan":"Plan","Home":"Acasă","Choose a plan":"Alege un plan","Rename Page":"Pagina de redenumire","Thumbnail Page":"Pagina miniaturii","Language Page":"Pagina limbii"} ,
    "ru": {"Custom Thumbnail":"Пользовательская миниатюра","Add Thumbnail":"Добавить миниатюру","Replace Thumbnail":"Заменить миниатюру","Show Thumbnail":"Показать миниатюру","Delete Custom":"Удалить пользовательскую","Plan":"План","Home":"Главная","Choose a plan":"Выберите план","Rename Page":"Страница переименования","Thumbnail Page":"Страница миниатюры","Language Page":"Страница языка"} ,
    "sr": {"Custom Thumbnail":"Прилагођена сличица","Add Thumbnail":"Додај сличицу","Replace Thumbnail":"Замени сличицу","Show Thumbnail":"Прикажи сличицу","Delete Custom":"Обриши прилагођену","Plan":"План","Home":"Почетна","Choose a plan":"Изаберите план","Rename Page":"Страница за преименовање","Thumbnail Page":"Страница сличице","Language Page":"Страница језика"} ,
    "sk": {"Custom Thumbnail":"Vlastná miniatúra","Add Thumbnail":"Pridať miniatúru","Replace Thumbnail":"Nahradiť miniatúru","Show Thumbnail":"Zobraziť miniatúru","Delete Custom":"Odstrániť vlastnú","Plan":"Plán","Home":"Domov","Choose a plan":"Vyberte plán","Rename Page":"Stránka premenovania","Thumbnail Page":"Stránka miniatúry","Language Page":"Stránka jazyka"} ,
    "sl": {"Custom Thumbnail":"Prilagojena sličica","Add Thumbnail":"Dodaj sličico","Replace Thumbnail":"Zamenjaj sličico","Show Thumbnail":"Prikaži sličico","Delete Custom":"Izbriši prilagojeno","Plan":"Načrt","Home":"Domov","Choose a plan":"Izberite načrt","Rename Page":"Stran za preimenovanje","Thumbnail Page":"Stran sličice","Language Page":"Stran jezika"} ,
    "es": {"Custom Thumbnail":"Miniatura personalizada","Add Thumbnail":"Añadir miniatura","Replace Thumbnail":"Reemplazar miniatura","Show Thumbnail":"Mostrar miniatura","Delete Custom":"Eliminar personalizada","Plan":"Plan","Home":"Inicio","Choose a plan":"Elige un plan","Rename Page":"Página de renombrado","Thumbnail Page":"Página de miniatura","Language Page":"Página de idioma"} ,
    "si": {"Custom Thumbnail":"අභිරුචි කුඩා රූපය","Add Thumbnail":"කුඩා රූපය එක් කරන්න","Replace Thumbnail":"කුඩා රූපය ප්‍රතිස්ථාපනය කරන්න","Show Thumbnail":"කුඩා රූපය පෙන්වන්න","Delete Custom":"අභිරුචිය මකන්න","Plan":"සැලැස්ම","Home":"මුල් පිටුව","Choose a plan":"සැලැස්මක් තෝරන්න","Rename Page":"නම වෙනස් කිරීමේ පිටුව","Thumbnail Page":"කුඩා රූප පිටුව","Language Page":"භාෂා පිටුව"} ,
    "sv": {"Custom Thumbnail":"Anpassad miniatyr","Add Thumbnail":"Lägg till miniatyr","Replace Thumbnail":"Ersätt miniatyr","Show Thumbnail":"Visa miniatyr","Delete Custom":"Ta bort anpassad","Plan":"Plan","Home":"Hem","Choose a plan":"Välj en plan","Rename Page":"Sida för namnbyte","Thumbnail Page":"Miniatyrsida","Language Page":"Språksida"} ,
    "th": {"Custom Thumbnail":"ภาพขนาดย่อกำหนดเอง","Add Thumbnail":"เพิ่มภาพขนาดย่อ","Replace Thumbnail":"แทนที่ภาพขนาดย่อ","Show Thumbnail":"แสดงภาพขนาดย่อ","Delete Custom":"ลบแบบกำหนดเอง","Plan":"แพ็กเกจ","Home":"หน้าหลัก","Choose a plan":"เลือกแพ็กเกจ","Rename Page":"หน้าการเปลี่ยนชื่อ","Thumbnail Page":"หน้าภาพขนาดย่อ","Language Page":"หน้าภาษา"} ,
    "ta": {"Custom Thumbnail":"தனிப்பயன் சிறுபடம்","Add Thumbnail":"சிறுபடத்தைச் சேர்","Replace Thumbnail":"சிறுபடத்தை மாற்று","Show Thumbnail":"சிறுபடத்தைக் காட்டு","Delete Custom":"தனிப்பயனை நீக்கு","Plan":"திட்டம்","Home":"முகப்பு","Choose a plan":"ஒரு திட்டத்தைத் தேர்ந்தெடுக்கவும்","Rename Page":"மறுபெயரிடும் பக்கம்","Thumbnail Page":"சிறுபடப் பக்கம்","Language Page":"மொழிப் பக்கம்"} ,
    "te": {"Custom Thumbnail":"కస్టమ్ థంబ్‌నెయిల్","Add Thumbnail":"థంబ్‌నెయిల్ జోడించు","Replace Thumbnail":"థంబ్‌నెయిల్ మార్చు","Show Thumbnail":"థంబ్‌నెయిల్ చూపించు","Delete Custom":"కస్టమ్ తొలగించు","Plan":"ప్లాన్","Home":"హోమ్","Choose a plan":"ఒక ప్లాన్ ఎంచుకోండి","Rename Page":"పేరు మార్చే పేజీ","Thumbnail Page":"థంబ్‌నెయిల్ పేజీ","Language Page":"భాష పేజీ"} ,
    "tr": {"Custom Thumbnail":"Özel küçük resim","Add Thumbnail":"Küçük resim ekle","Replace Thumbnail":"Küçük resmi değiştir","Show Thumbnail":"Küçük resmi göster","Delete Custom":"Özeli sil","Plan":"Plan","Home":"Ana Sayfa","Choose a plan":"Bir plan seçin","Rename Page":"Yeniden adlandırma sayfası","Thumbnail Page":"Küçük resim sayfası","Language Page":"Dil sayfası"} ,
    "uk": {"Custom Thumbnail":"Власна мініатюра","Add Thumbnail":"Додати мініатюру","Replace Thumbnail":"Замінити мініатюру","Show Thumbnail":"Показати мініатюру","Delete Custom":"Видалити власну","Plan":"План","Home":"Головна","Choose a plan":"Оберіть план","Rename Page":"Сторінка перейменування","Thumbnail Page":"Сторінка мініатюри","Language Page":"Сторінка мови"} ,
    "ur": {"Custom Thumbnail":"حسب ضرورت تھمب نیل","Add Thumbnail":"تھمب نیل شامل کریں","Replace Thumbnail":"تھمب نیل تبدیل کریں","Show Thumbnail":"تھمب نیل دکھائیں","Delete Custom":"حسب ضرورت حذف کریں","Plan":"پلان","Home":"ہوم","Choose a plan":"ایک پلان منتخب کریں","Rename Page":"نام تبدیل کرنے کا صفحہ","Thumbnail Page":"تھمب نیل صفحہ","Language Page":"زبان کا صفحہ"} ,
    "uz": {"Custom Thumbnail":"Maxsus eskiz","Add Thumbnail":"Eskiz qo‘shish","Replace Thumbnail":"Eskizni almashtirish","Show Thumbnail":"Eskizni ko‘rsatish","Delete Custom":"Maxsusni o‘chirish","Plan":"Reja","Home":"Bosh sahifa","Choose a plan":"Rejani tanlang","Rename Page":"Nomini o‘zgartirish sahifasi","Thumbnail Page":"Eskiz sahifasi","Language Page":"Til sahifasi"} ,
    "vi": {"Custom Thumbnail":"Ảnh thu nhỏ tùy chỉnh","Add Thumbnail":"Thêm ảnh thu nhỏ","Replace Thumbnail":"Thay ảnh thu nhỏ","Show Thumbnail":"Hiển thị ảnh thu nhỏ","Delete Custom":"Xóa ảnh tùy chỉnh","Plan":"Gói","Home":"Trang chủ","Choose a plan":"Chọn một gói","Rename Page":"Trang đổi tên","Thumbnail Page":"Trang ảnh thu nhỏ","Language Page":"Trang ngôn ngữ"} ,
}


def tr(lang: str | None, key: str) -> str:
    code = str(lang or "en").lower()
    data = EXTENDED_STRINGS.get(code) or EXTENDED_STRINGS["en"]
    if key == "Custom Thumbnail" and key not in data:
        return STRINGS.get(code, STRINGS["en"]).get("Permanent Thumbnail", key)
    return data.get(key) or STRINGS.get(code, STRINGS["en"]).get(key) or key


def localize_markup(markup, lang: str | None):
    """Return a copy of an inline keyboard with all known UI labels localized."""
    if markup is None:
        return None
    from pyrogram.types import InlineKeyboardButton, InlineKeyboardMarkup
    rows = []
    for row in getattr(markup, "inline_keyboard", []) or []:
        new_row = []
        for button in row:
            text = getattr(button, "text", "") or ""
            clean = text
            if clean.startswith("🖼 Permanent Thumbnail") or clean.startswith("🖼 Custom Thumbnail"):
                localized = tr(lang, "Custom Thumbnail")
                clean = "🖼 " + localized
            elif clean.startswith("➕ Add Thumbnail"):
                clean = "➕ " + tr(lang, "Add Thumbnail")
            elif clean.startswith("🔄 Replace Thumbnail"):
                clean = "🔄 " + tr(lang, "Replace Thumbnail")
            elif clean.startswith("👁 Show Thumbnail"):
                clean = "👁 " + tr(lang, "Show Thumbnail")
            elif clean.startswith("🗑 Delete Custom"):
                clean = "🗑 " + tr(lang, "Delete Custom")
            elif clean.startswith("💎 Plan"):
                clean = "💎 " + tr(lang, "Plan")
            elif clean.startswith("🔙 Back"):
                clean = "🔙 " + tr(lang, "Back")
            elif clean.startswith("🔙 Settings"):
                clean = "🔙 " + tr(lang, "Settings")
            elif clean.startswith("🛠 Help"):
                clean = "🛠 " + tr(lang, "Help")
            elif clean.startswith("⚙️ Settings"):
                clean = "⚙️ " + tr(lang, "Settings")
            elif clean.startswith("✏️ Rename"):
                clean = "✏️ " + tr(lang, "Rename")
            elif clean.startswith("❌ Cancel"):
                clean = "❌ " + tr(lang, "Cancel")
            elif clean.startswith("✅ Confirm"):
                clean = "✅ " + tr(lang, "Confirm")
            elif clean.startswith("🚫 No Thumbnail"):
                clean = "🚫 " + tr(lang, "No Thumbnail")
            elif clean.startswith("🤖 Auto Thumbnail"):
                clean = "🤖 " + tr(lang, "Auto Thumbnail")
            elif clean.startswith("🌐 Language"):
                clean = "🌐 " + tr(lang, "Language")
            elif clean.startswith("🏷 Metadata"):
                clean = "🏷 " + tr(lang, "Metadata")
            new_row.append(InlineKeyboardButton(clean, callback_data=getattr(button,"callback_data",None), url=getattr(button,"url",None), web_app=getattr(button,"web_app",None), login_url=getattr(button,"login_url",None), switch_inline_query=getattr(button,"switch_inline_query",None), switch_inline_query_current_chat=getattr(button,"switch_inline_query_current_chat",None), callback_game=getattr(button,"callback_game",None), pay=getattr(button,"pay",False)))
        rows.append(new_row)
    return InlineKeyboardMarkup(rows)
